# Generated by Django 3.0.4 on 2020-03-23 21:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('dataNasc', models.DateField()),
                ('genero', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=50)),
                ('tipoSang', models.CharField(max_length=50)),
                ('sintomas', models.CharField(max_length=150)),
                ('descrCaso', models.TextField()),
                ('gravidade', models.CharField(max_length=50)),
                ('dataInc', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
