# Generated by Django 3.0.4 on 2020-03-24 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='diagnosticos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.CharField(choices=[('Covid-19', 'Covid-19'), ('Influenza', 'Influenza'), ('Influenza H1N1', 'Influenza H1N1'), ('Influenza H5N1', 'Influenza H5N1')], max_length=50)),
                ('Pacientes', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.Pacientes')),
            ],
        ),
    ]
